# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: enemies_list-api_development

test:
  <<: *default
  database: enemies_list-api_test

production:
  <<: *default
  database: enemies_list-api_production
  username: enemies_list-api
  password: <%= ENV['ENEMIES_LIST-API_DATABASE_PASSWORD'] %>